# Generated by Django 5.1.4 on 2024-12-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='organization',
        ),
    ]
